apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
  namespace: marketplace
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  AUTH_DB_HOST: "auth-postgres-service"
  AUTH_DB_PORT: "5432"
  AUTH_DB_NAME: "marketplace-auth"
