# Deployment untuk Orders
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: marketplace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: tugas1_sol-orders
        ports:
        - containerPort: 8002
        env:
        - name: TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: TENANT_ID
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: marketplace-secret
              key: JWT_SECRET
        - name: PRODUCT_MS_URL
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: PRODUCTS_API_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: ORDERS_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: ORDERS_DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: ORDERS_DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: marketplace-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: marketplace-secret
              key: DB_PASSWORD
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

# Service untuk Orders (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: marketplace
spec:
  type: NodePort
  selector:
    app: orders
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30002