apiVersion: v1
kind: Namespace
metadata:
  name: marketplace

---
# Persistent Volumes (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/auth-db"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/orders-db"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: products-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/products-db"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tenant-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/tenant-db"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wishlist-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/wishlist-db"

---
# Persistent Volume Claims (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeName: auth-db-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeName: orders-db-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-db-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeName: products-db-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenant-db-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeName: tenant-db-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wishlist-db-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeName: wishlist-db-pv

---
# PostgreSQL Deployments and Services
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: auth_db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: auth-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: marketplace
spec:
  type: ClusterIP
  selector:
    app: auth-db
  ports:
    - port: 5432
      targetPort: 5432

---
# Orders DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-db
  template:
    metadata:
      labels:
        app: orders-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orders_db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: orders-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: marketplace
spec:
  type: ClusterIP
  selector:
    app: orders-db
  ports:
    - port: 5432
      targetPort: 5432

---
# Products DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: products_db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: products-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: products-db
  namespace: marketplace
spec:
  type: ClusterIP
  selector:
    app: products-db
  ports:
    - port: 5432
      targetPort: 5432

---
# Tenant DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-db
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-db
  template:
    metadata:
      labels:
        app: tenant-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: tenant_db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: tenant-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-db
  namespace: marketplace
spec:
  type: ClusterIP
  selector:
    app: tenant-db
  ports:
    - port: 5432
      targetPort: 5432

---
# Wishlist DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-db
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-db
  template:
    metadata:
      labels:
        app: wishlist-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: wishlist_db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: wishlist-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-db
  namespace: marketplace
spec:
  type: ClusterIP
  selector:
    app: wishlist-db
  ports:
    - port: 5432
      targetPort: 5432
