# Deployment untuk Tenant
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-deployment
  namespace: marketplace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
      - name: tenant
        image: tugas1_sol-tenant
        ports:
        - containerPort: 8004
        env:
        - name: TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: TENANT_ID
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: marketplace-secret
              key: JWT_SECRET
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: AUTH_API_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: TENANT_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: TENANT_DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: TENANT_DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: marketplace-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: marketplace-secret
              key: DB_PASSWORD
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: tenant-storage
          mountPath: "/data"
      volumes:
      - name: tenant-storage
        persistentVolumeClaim:
          claimName: tenant-pvc

# Service untuk Tenant (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: tenant-service
  namespace: marketplace
spec:
  type: NodePort
  selector:
    app: tenant
  ports:
  - port: 8004
    targetPort: 8004
    nodePort: 30004

# Persistent Volume Claim untuk Tenant
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenant-pvc
  namespace: marketplace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard